{-# LANGUAGE OverloadedStrings #-}
{-- WARNING! This file is automatically generated!
Do not edit this file - instead, run util/build-amf-elements.hs
--}
module Graphics.Implicit.Export.Additive.Elements (
Markup (..), vertex, coordinates, normal, amf, object, mesh, volume, triangle, vertices, x, y, z, nx, ny, nz, v1, v2, v3
) where
import Text.Blaze.Internal

x :: Show a => a -> Markup
x a = Parent "x" "<x" "</x>" $ Content $ PreEscaped $ String $ show a
{-# INLINE x #-}

y :: Show a => a -> Markup
y a = Parent "y" "<y" "</y>" $ Content $ PreEscaped $ String $ show a
{-# INLINE y #-}

z :: Show a => a -> Markup
z a = Parent "z" "<z" "</z>" $ Content $ PreEscaped $ String $ show a
{-# INLINE z #-}

nx :: Show a => a -> Markup
nx a = Parent "nx" "<nx" "</nx>" $ Content $ PreEscaped $ String $ show a
{-# INLINE nx #-}

ny :: Show a => a -> Markup
ny a = Parent "ny" "<ny" "</ny>" $ Content $ PreEscaped $ String $ show a
{-# INLINE ny #-}

nz :: Show a => a -> Markup
nz a = Parent "nz" "<nz" "</nz>" $ Content $ PreEscaped $ String $ show a
{-# INLINE nz #-}

v1 :: Show a => a -> Markup
v1 a = Parent "v1" "<v1" "</v1>" $ Content $ PreEscaped $ String $ show a
{-# INLINE v1 #-}

v2 :: Show a => a -> Markup
v2 a = Parent "v2" "<v2" "</v2>" $ Content $ PreEscaped $ String $ show a
{-# INLINE v2 #-}

v3 :: Show a => a -> Markup
v3 a = Parent "v3" "<v3" "</v3>" $ Content $ PreEscaped $ String $ show a
{-# INLINE v3 #-}


vertex :: Markup -> Markup
vertex = Parent "vertex" "<vertex" "</vertex>"
{-# INLINE vertex #-}

coordinates :: Markup -> Markup
coordinates = Parent "coordinates" "<coordinates" "</coordinates>"
{-# INLINE coordinates #-}

normal :: Markup -> Markup
normal = Parent "normal" "<normal" "</normal>"
{-# INLINE normal #-}

amf :: Markup -> Markup
amf = Parent "amf" "<amf" "</amf>"
{-# INLINE amf #-}

object :: Markup -> Markup
object = Parent "object" "<object" "</object>"
{-# INLINE object #-}

mesh :: Markup -> Markup
mesh = Parent "mesh" "<mesh" "</mesh>"
{-# INLINE mesh #-}

volume :: Markup -> Markup
volume = Parent "volume" "<volume" "</volume>"
{-# INLINE volume #-}

triangle :: Markup -> Markup
triangle = Parent "triangle" "<triangle" "</triangle>"
{-# INLINE triangle #-}

vertices :: Markup -> Markup
vertices = Parent "vertices" "<vertices" "</vertices>"
{-# INLINE vertices #-}


